### ISSUE TITLE
[Blocker] "Print" button inside wp-admin dashboard is not working. 

### ISSUE THREAD

**Issue by vedanshujain** [wceu/camptix-invoices#23]
Looks I am not able to get the "Print" button inside the dashboard to work. This is the error log (it could be because I have noticed enabled 🤔  )
```

Notice: Undefined offset: 1 in /usr/src/public_html/wp-content/plugins/invoices-camptix/includes/lib/fpdf/invoicePDF.php on line 343

Notice: Undefined offset: 1 in /usr/src/public_html/wp-content/plugins/invoices-camptix/includes/lib/fpdf/invoicePDF.php on line 343

Notice: Undefined offset: 1 in /usr/src/public_html/wp-content/plugins/invoices-camptix/includes/lib/fpdf/invoicePDF.php on line 349

Notice: Undefined offset: 1 in /usr/src/public_html/wp-content/plugins/invoices-camptix/includes/lib/fpdf/invoicePDF.php on line 343

Notice: Undefined offset: 1 in /usr/src/public_html/wp-content/plugins/invoices-camptix/includes/lib/fpdf/invoicePDF.php on line 343

Notice: Undefined offset: 1 in /usr/src/public_html/wp-content/plugins/invoices-camptix/includes/lib/fpdf/invoicePDF.php on line 349

Fatal error: Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file in /usr/src/public_html/wp-content/plugins/invoices-camptix/includes/lib/fpdf/fpdf.php:271 Stack trace: #0 /usr/src/public_html/wp-content/plugins/invoices-camptix/includes/lib/fpdf/fpdf.php(1063): FPDF->Error('Some data has a...') #1 /usr/src/public_html/wp-content/plugins/invoices-camptix/includes/lib/fpdf/fpdf.php(1012): FPDF->_checkoutput() #2 /usr/src/public_html/wp-content/plugins/invoices-camptix/camptix-invoices.php(521): FPDF->Output('D', 'invoice-3.pdf') #3 /usr/src/public_html/wp-content/plugins/invoices-camptix/camptix-invoices.php(418): ctx_get_invoice(295) #4 /usr/src/public_html/wp-includes/class-wp-hook.php(286): ctx_download_invoice('') #5 /usr/src/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #6 /usr/src/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #7 /usr/src/public_html/wp-admin/admin-post.php(69): do_action('admin_post_camp...') #8 {main} throw in /usr/src/public_html/wp-content/plugins/invoices-camptix/includes/lib/fpdf/fpdf.php on line 271
```

Although invoice in mail seems to be working fine.

**Comment by iandunn** [comment]
This might be unnecessary if #20 is done first.

**Comment by avillegasn** [comment]
383160487434fdeda17f461230a8f66b9dbe6a0a removes all files from fpdf.
